version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:18.11.0
    steps:
      - checkout
      - run:
          name: node version
          command: "node -v"
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test